name: Nightly CI
on:
  workflow_dispatch:
  # add input for email address
    inputs:
      email:
        description: 'Email address to send report to'
        required: true
        default: 'ravi1.gupta@intel.com'
  schedule:
#   - cron: '0 0 * * *' # every 24 hrs
    - cron: '30 19 * * *' # runs every day at 19:30 pm UTC which is 11:30 am PST
jobs:
  invoke-sync:
    runs-on: gpu
    steps:
      - name: Retrieve version
        run: |
          echo "TAG_NAME=$(pwd)" >> $GITHUB_OUTPUT
      - name: Invoke Sync
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: Sync to Upstream Public Repo
          token: ${{secrets.IMEX_CI_RAVI_GH}}
          
  invoke-cpu-tests:
    runs-on: gpu
    needs: invoke-sync
    steps:
      - name: Invoke main Build_CPU Workflow
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: CPU Build
          token: ${{secrets.WORKFLOW_TOKEN}}

      - name: Invoke numba-dev Build_CPU Workflow
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: CPU Build
          ref: numba-dev
          token: ${{secrets.WORKFLOW_TOKEN}}
          
  invoke-gpu-tests:
    runs-on: gpu
    needs: invoke-cpu-tests
    steps:
      - name: Invoke numba-dev Build_GPU Workflow
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: GPU Build
          ref: numba-dev
          token: ${{secrets.WORKFLOW_TOKEN}}

      - name: Invoke main Build_GPU Workflow
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: GPU Build
          token: ${{secrets.WORKFLOW_TOKEN}}

  generate_report:
    runs-on: gpu
    needs: invoke-gpu-tests
    steps:
      - name: Echo Report info
        run: echo "sending to ravi1.gupta@intel.com by default trigger."

      - name: Send Report
      # run this only if workflow dispatch is not called
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: Send Report
          inputs: '{ "email": "aia.core.mlir.compiler@intel.com"}'
          token: ${{secrets.WORKFLOW_TOKEN}}

      - name: Send Report
        # send report using this if workflow dispatch is called
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: intel-innersource/frameworks.actions.thirdparty.workflow-dispatch@v1
        with:
          workflow: Send Report
          inputs: '{ "email": "${{ github.event.inputs.email }}"}'
          token: ${{secrets.WORKFLOW_TOKEN}}
